import { NextResponse } from 'next/server';
import crypto from 'crypto';
import sha256 from 'crypto-js/sha256';
import { v4 as uuidv4 } from 'uuid';
import { createNewStoreOrder } from '../../../../lib/appwrite/ecomDatabase'; // Order creation logic
import { getBaseUrl, getPhonepeUrl } from '../../../../lib/constants';

export async function POST(req) {
	try {
		// Extract data from the request body
		const {
			cartItems,
			amount,
			customerName,
			shippingAddress,
			pincode,
			state,
			city,
			email,
			phoneNumber,
		} = await req.json();

		// Generate a unique merchantTransactionId
		const merchantTransactionId = crypto.randomBytes(16).toString('hex');

		// Create the order in the database
		const order = await createNewStoreOrder({
			cartItems,
			cartTotal: amount / 100, // Convert paise back to INR
			customerName,
			shippingAddress,
			pincode,
			state,
			city,
			email,
			phoneNumber,
			orderStatus: 'PENDING', // Initial order status
			merchantTransactionId,
		});

		// Use the getBaseUrl function to dynamically get the base URL
		const baseUrl = getBaseUrl();

		// Generate MUID (merchantUserId)
		const merchantUserId = `MUID-${uuidv4()}`;

		// Construct the payment payload
		const payload = {
			merchantId: process.env.PHONEPE_MERCHANT_ID,
			merchantTransactionId, // Generated by backend
			merchantUserId,
			amount, // in paise (10000 for 100 INR)
			redirectUrl: `${baseUrl}/api/payment/status/${merchantTransactionId}`, // Use dynamic base URL
			redirectMode: 'POST',
			callbackUrl: `${baseUrl}/api/payment/status/${merchantTransactionId}`, // Use dynamic base URL
			mobileNumber: phoneNumber,
			paymentInstrument: {
				type: 'PAY_PAGE',
			},
		};

		// Convert payload to base64
		const base64Payload = Buffer.from(JSON.stringify(payload)).toString(
			'base64'
		);

		// Generate checksum using sha256
		const fullUrl = base64Payload + '/pg/v1/pay' + process.env.PHONEPE_SALT_KEY;
		const checksum =
			sha256(fullUrl).toString() + '###' + process.env.PHONEPE_SALT_INDEX;

		// Prepare the request options for PhonePe's API
		const options = {
			method: 'POST',
			headers: {
				accept: 'application/json',
				'Content-Type': 'application/json',
				'X-VERIFY': checksum,
			},
			body: JSON.stringify({ request: base64Payload }),
		};

		// Send the request to PhonePe's API
		const PAY_API_URL = `${getPhonepeUrl()}/pay`;
		const response = await fetch(PAY_API_URL, options);
		const result = await response.json();

		if (result.success) {
			return NextResponse.json(result);
		} else {
			return NextResponse.json(
				{ error: 'Payment initiation failed' },
				{ status: 500 }
			);
		}
	} catch (error) {
		return NextResponse.json(
			{ error: 'Payment initiation failed', details: error.message },
			{ status: 500 }
		);
	}
}
