export const consultations = [
	{
		title: 'Name Correction',
		slug: 'name-correction',
		tagline: 'Unlock the power of your name with our specialised',
		description:
			'Names hold significant vibrational energy that can influence various aspects of your life, from personal relationships to professional success. Our expert numerologist, Prakritii Vermaa, employs ancient numerological techniques to analyze and correct your name for optimal harmony and prosperity.',
		link: '/consultations/name-correction',
		image: '/images/services/name-correction.webp',
		currentPrice: 5100,
		actualPrice: Math.ceil(5100 / 0.7),
		offering: [
			'Detailed Name Analysis: Using Chaldean, Pythagorean and Vedic charts, we provide a comprehensive analysis of your name.',
			'Personalized Correction: Tailored name corrections that align with your personal numerology and life goals.',
			'Energy Enhancement: Enhance the vibrational energy of your name to attract positive opportunities and experiences.',
			'Professional Guidance: Receive one-to-one counseling to understand the significance of the changes and how to integrate them into your life.',
		],
		benefits: [
			'Improved personal and professional relationships',
			'Increased confidence and self-awareness',
			'Enhanced opportunities and success',
			'Greater harmony and balance in life',
		],
	},
	{
		title: 'Mobile Number Correction/Suggestion',
		slug: 'mobile-number-correction',
		tagline: 'Your mobile number is more than just a means of communication',
		description:
			'Your mobile number holds a unique vibrational energy that can impact your life. Our expert numerologist, Prakritii Vermaa, will analyze and adjust your mobile number to align with your personal numerology, enhancing your life’s potential.',
		link: '/consultations/mobile-number-correction',
		image: '/images/services/mobile-number-correction.webp',
		currentPrice: 5100,
		actualPrice: Math.ceil(5100 / 0.7),
		offering: [
			'Comprehensive Analysis: Detailed analysis of your current mobile number using numerological techniques.',
			'Personalized Recommendations: Suggestions for a new number or modifications to your existing number that harmonize with your life path and goals.',
			'Enhanced Vibrational Energy: Optimize the energetic influence of your mobile number to attract positivity and success.',
			'Professional Guidance: One-to-one counseling to explain the changes and their potential impact on your life.',
		],
		benefits: [
			'Improved personal and professional relationships',
			'Increased luck and opportunities',
			'Enhanced mental clarity and decision-making',
			'Greater overall harmony and balance',
		],
	},
	{
		title: 'Personal Consultation',
		slug: 'personal-consultation',
		tagline: 'Unlock Your Destiny with Our Numerology Consultation',
		description:
			'Embark on a transformative journey with our expert numerology consultation. Renowned numerologist Prakritii Vermaa will guide you through a personalized analysis, revealing deep insights into your personality, relationships, career, and life purpose.',
		link: '/consultations/personal-consultation',
		image: '/images/services/personal-consultation.webp',
		currentPrice: 7100,
		actualPrice: Math.ceil(7100 / 0.7),
		offering: [
			'In-Depth Numerological Analysis: Decode the significance of your birth date and name, unveiling your unique numerical blueprint.',
			'Personalized Insights and Guidance: Gain clarity on your life path, destiny number, soul urge number, and more.',
			'Strategic Life Advice: Practical and actionable advice on career choices, relationships, health, and personal growth.',
			'Crystal Recommendations: Discover crystals that resonate with your numerological profile.',
			'Special Remedies and Vastu Consultation: Personalized remedies and Vastu advice to create harmony in your environment.',
		],
		benefits: [
			'Clarity on life path and personal purpose',
			'Increased opportunities for personal and professional growth',
			'Practical strategies for overcoming challenges',
			'Holistic approach to balancing personal and professional life',
		],
	},
	{
		title: 'Business Consultation',
		slug: 'business-consultation',
		tagline: 'Elevate Your Business with Our Strategic Numerology Consultation',
		description:
			"Unlock the hidden potential of your business with our specialized numerology consultation. Whether you're a startup or an established enterprise, Prakritii Vermaa provides strategic insights to enhance your business success.",
		link: '/consultations/business-consultation',
		image: '/images/services/business-consultation.webp',
		currentPrice: 9100,
		actualPrice: Math.ceil(9100 / 0.7),
		offering: [
			'Business Name Analysis and Correction: Ensure your business name resonates with success and attracts positive energies.',
			'Strategic Planning: Identify optimal times for launching new products or making significant business decisions.',
			'Employee and Team Analysis: Gain insights into your team members’ numerological profiles for a harmonious work environment.',
			'Financial Forecasting: Receive numerological guidance on financial planning, investments, and cash flow management.',
			'Vastu Consultation: Harmonize your office space with Vastu principles to enhance productivity and success.',
		],
		benefits: [
			'Improved brand resonance and market appeal',
			'Enhanced decision-making and strategic planning',
			'Greater team harmony and productivity',
			'Optimal financial management and growth',
		],
	},
	{
		title: 'Company Name Correction for Proprietor/Partnership Company',
		slug: 'company-name-correction-proprietor',
		tagline:
			'Enhance Your Business Success with Our Company Name Correction Service',
		description:
			"Your company name is a powerful tool that can influence your business's success. Ensure it aligns with positive numerological principles to attract prosperity and growth.",
		link: '/consultations/company-name-correction-proprietor',
		image: '/images/services/company-name-correction-proprietor.webp',
		currentPrice: 9100,
		actualPrice: Math.ceil(9100 / 0.7),
		offering: [
			'Comprehensive Name Analysis: In-depth analysis of your current company name using numerological charts.',
			'Personalized Name Corrections: Tailored recommendations for name modifications that align with your business goals.',
			'Strategic Alignment: Ensure your company name resonates with success, attracting positive opportunities.',
			'Enhanced Branding: Improve the energetic appeal of your brand, making it more attractive to customers and investors.',
		],
		benefits: [
			'Increased business opportunities and growth',
			'Enhanced brand recognition and market appeal',
			'Improved client and partner relationships',
			'Greater financial stability and success',
		],
	},
	{
		title: 'Company Name Correction for Pvt Ltd',
		slug: 'company-name-correction-pvt-ltd',
		tagline:
			'Optimize Your Private Limited Company&apos;s Success with Our Name Correction Service',
		description:
			"Optimize your Private Limited Company's success with a numerologically aligned name. Expert numerologist Prakritii Vermaa offers personalized name corrections to drive growth and prosperity.",
		link: '/consultations/company-name-correction-pvt-ltd',
		image: '/images/services/company-name-correction-pvt-ltd.webp',
		currentPrice: 5100,
		actualPrice: Math.ceil(5100 / 0.7),
		offering: [
			'Detailed Name Analysis: Thorough analysis of your company name using numerology charts.',
			'Customized Name Corrections: Personalized recommendations for name adjustments to enhance brand success.',
			'Strategic Brand Enhancement: Ensure your company name enhances brand recognition and growth.',
			'Professional Consultation: Receive one-to-one guidance on implementing name corrections in business operations.',
		],
		benefits: [
			'Increased business opportunities and growth',
			'Enhanced brand recognition and market presence',
			'Improved client and stakeholder relationships',
			'Greater financial stability and success',
		],
	},
	{
		title: 'Missing Number Remedies',
		slug: 'missing-number-remedies',
		tagline: 'Harmonize Your Life with Our Missing Number Remedies',
		description:
			'Address the missing numbers in your numerology chart to bring balance and harmony to your life. Our expert remedies can help you overcome challenges and enhance your strengths.',
		link: '/consultations/missing-number-remedies',
		image: '/images/services/missing-number-remedies.webp',
		currentPrice: 2100,
		actualPrice: Math.ceil(2100 / 0.7),
		offering: [
			'Comprehensive Chart Analysis: Identify any missing numbers in your numerology chart and understand their impact.',
			'Personalized Remedies: Tailored remedies to address missing numbers and balance your life energies.',
			'Energy Enhancement Techniques: Implement affirmations, crystals, and lifestyle changes to integrate the missing energies.',
			'Ongoing Support: Follow-up consultations to ensure the effectiveness of remedies.',
		],
		benefits: [
			'Improved personal and professional relationships',
			'Increased confidence and self-awareness',
			'Greater balance and harmony in life',
			'Enhanced success and opportunities',
		],
	},
	{
		title: 'Career and Finance Counseling',
		slug: 'career-and-finance-counseling',
		tagline: 'Unlock Your Potential with Our Career and Finance Consultation',
		description:
			'Achieve success in your career and manage your finances effectively with the guidance of renowned numerologist Prakritii Vermaa. Align your career and financial goals with your unique numerological profile for greater success.',
		link: '/consultations/career-and-finance-counseling',
		image: '/images/services/career-and-finance-counseling.webp',
		currentPrice: 5100,
		actualPrice: Math.ceil(5100 / 0.7),
		offering: [
			'Comprehensive Numerology Analysis: Detailed analysis using Chaldean, Pythagorean, and Vedic numerology charts to uncover numerical influences on your career and financial prospects.',
			'Personalized Career Guidance: Discover your strengths, talents, and ideal career paths.',
			'Financial Insights and Planning: Gain insights into your financial habits and potential.',
			'Strategic Timing: Identify the most auspicious times for career moves or financial decisions.',
			'Professional Support: One-to-one counseling to discuss your goals and challenges.',
		],
		benefits: [
			'Clarity and direction in your career path',
			'Enhanced decision-making for job changes and promotions',
			'Improved financial management and investment strategies',
			'Increased opportunities for career growth and financial success',
			'Greater alignment with your life purpose and goals',
		],
	},
	{
		title: 'Relationship Counseling',
		slug: 'relationship-counseling',
		tagline: 'Enhance Your Relationships with Our Expert Consultation',
		description:
			'Transform your relationships with expert numerological guidance. Enhance your communication, compatibility, and emotional connection in your relationships with tailored advice from renowned numerologist Prakritii Vermaa.',
		link: '/consultations/relationship-counseling',
		image: '/images/services/relationship-counseling.webp',
		currentPrice: 5100,
		actualPrice: Math.ceil(5100 / 0.7),
		offering: [
			'Comprehensive Relationship Analysis: Using numerology charts to analyze the compatibility between you and your partner or significant others.',
			'Personalized Insights: Receive detailed guidance on enhancing communication and resolving conflicts.',
			'Compatibility Assessments: Assess compatibility with potential partners, friends, or colleagues.',
			'Conflict Resolution Strategies: Practical advice and remedies for resolving relationship conflicts.',
			'Professional Counseling: Enjoy one-to-one sessions for tailored advice.',
		],
		benefits: [
			'Enhanced understanding and communication in relationships',
			'Improved compatibility and harmony with partners, friends, and colleagues',
			'Effective strategies for resolving conflicts',
			'Greater emotional connection and satisfaction',
			'Personal growth and better relationship dynamics',
		],
	},
	{
		title: 'Yantra Recommendation',
		slug: 'yantra-recommendation',
		tagline: 'Elevate Your Energies with Our Yantra Recommendation Service',
		description:
			'Unlock the power of ancient yantras to bring balance, prosperity, and spiritual growth into your life. Expert numerologist Prakritii Vermaa offers personalized yantra recommendations tailored to your unique numerological profile.',
		link: '/consultations/yantra-recommendation',
		image: '/images/services/yantra-recommendation.webp',
		currentPrice: 3100,
		actualPrice: Math.ceil(3100 / 0.7),
		offering: [
			'Personalized Yantra Analysis: Assess your numerological profile and life goals to recommend appropriate yantras.',
			'Detailed Yantra Selection: Yantras tailored to your personal or professional goals.',
			'Integration Guidance: Advice on placement, usage, and meditation techniques.',
			'Energy Enhancement Techniques: Practices to enhance the energetic benefits of yantras.',
			'Hand Made Prepared: Personalized and handmade Yantras prepared during the best Muhurt.',
		],
		benefits: [
			'Enhanced focus and alignment with goals',
			'Improved prosperity, health, and spiritual growth',
			'Greater harmony and balance',
			'Increased success and positive energy flow',
		],
	},
	{
		title: 'Vehicle and Property Consultation & Remedies',
		slug: 'vehicle-property-consultation',
		tagline:
			'Optimize Your Vehicle and Property Choices with Our Expert Consultation',
		description:
			'Make informed and harmonious decisions for your vehicle and property with expert numerological guidance. Numerologist Prakritii Vermaa helps you align these decisions with positive energies to enhance your success and well-being.',
		link: '/consultations/vehicle-property-consultation',
		image: '/images/services/vehicle-property-consultation.webp',
		currentPrice: 5100,
		actualPrice: Math.ceil(5100 / 0.7),
		offering: [
			'Comprehensive Numerology Analysis: Insights into optimal vehicle and property choices based on your numerology.',
			'Vehicle Recommendations: Personalized guidance on selecting a vehicle that aligns with your profile.',
			'Property Selection: Expert advice on choosing properties that resonate with positive energies.',
			'Numerological Optimization: Advice on customization, usage, and maintenance.',
			'Professional Consultation: One-to-one sessions for tailored recommendations.',
		],
		benefits: [
			'Enhanced satisfaction with your vehicle and property',
			'Improved alignment with personal and professional goals',
			'Greater harmony and positive energy flow',
			'Informed decisions for better investment and lifestyle choices',
		],
	},
	{
		title: 'Vedic Remedies',
		slug: 'vedic-remedies',
		tagline: 'Transform Your Life with Our Vedic Remedies Consultation',
		description:
			'Unlock the power of Vedic remedies to balance energies, resolve challenges, and enhance prosperity. Expert numerologist Prakritii Vermaa offers personalized consultations to guide you through effective remedies tailored to your unique needs.',
		link: '/consultations/vedic-remedies',
		image: '/images/services/vedic-remedies.webp',
		currentPrice: 3100,
		actualPrice: Math.ceil(3100 / 0.7),
		offering: [
			'Personalized Vedic Analysis: In-depth analysis of your Vedic astrological chart.',
			'Customized Remedies: Tailored mantras, yantras, gemstones, and ritual practices.',
			'Practical Implementation Guidance: Step-by-step instructions for implementing remedies.',
			'Energy Balancing Techniques: Techniques for harmonizing energies.',
			'One-on-One Consultation: Personal sessions to discuss concerns and receive bespoke recommendations.',
		],
		benefits: [
			'Resolution of personal and professional challenges',
			'Enhanced prosperity, health, and well-being',
			'Improved alignment with positive planetary influences',
			'Greater harmony and balance',
		],
	},
	{
		title: 'Energized Crystal Recommendation',
		slug: 'energized-crystal-recommendation',
		tagline: 'Enhance Your Life with Our Crystal Recommendation Service',
		description:
			'Enhance your life with personalized crystal recommendations. Prakritii Vermaa combines numerology with crystal healing to guide you in selecting the perfect crystals for emotional healing, spiritual growth, and personal goals.',
		link: '/consultations/energized-crystal-recommendation',
		image: '/images/services/energized-crystal-recommendation.webp',
		currentPrice: 3100,
		actualPrice: Math.ceil(3100 / 0.7),
		offering: [
			'Personalized Crystal Analysis: Crystals tailored to your numerological profile and life goals.',
			'Customized Recommendations: Guidance on selecting crystals for emotional healing, focus, or spiritual growth.',
			'Effective Usage Tips: Instructions on how to cleanse, charge, and meditate with your crystals.',
			'Complementary Practices: Techniques that enhance crystal benefits through affirmations and rituals.',
			'Professional Consultation: One-on-one sessions to discuss goals and challenges.',
		],
		benefits: [
			'Improved emotional balance and healing',
			'Enhanced focus, clarity, and spiritual growth',
			'Greater alignment with personal and professional goals',
			'Increased positive energy and well-being',
		],
	},
	{
		title: 'Test Details: Energized Crystal Recommendation',
		slug: 'energized-crystal-recommendation',
		tagline: 'Enhance Your Life with Our Crystal Recommendation Service',
		description:
			'Enhance your life with personalized crystal recommendations. Prakritii Vermaa combines numerology with crystal healing to guide you in selecting the perfect crystals for emotional healing, spiritual growth, and personal goals.',
		link: '/consultations/energized-crystal-recommendation',
		image: '/images/services/energized-crystal-recommendation.webp',
		currentPrice: 1,
		actualPrice: 1,
		offering: [
			'Personalized Crystal Analysis: Crystals tailored to your numerological profile and life goals.',
			'Customized Recommendations: Guidance on selecting crystals for emotional healing, focus, or spiritual growth.',
			'Effective Usage Tips: Instructions on how to cleanse, charge, and meditate with your crystals.',
			'Complementary Practices: Techniques that enhance crystal benefits through affirmations and rituals.',
			'Professional Consultation: One-on-one sessions to discuss goals and challenges.',
		],
		benefits: [
			'Improved emotional balance and healing',
			'Enhanced focus, clarity, and spiritual growth',
			'Greater alignment with personal and professional goals',
			'Increased positive energy and well-being',
		],
	},
];
