export const consultations = [
	{
		title: 'Name Correction',
		slug: 'name-correction',
		tagline: 'Unlock the power of your name with our specialised',
		description:
			'Names hold significant vibrational energy that can influence various aspects of your life, from personal relationships to professional success. Our expert numerologist, Akreti Verma, employs ancient numerological techniques to analyze and correct your name for optimal harmony and prosperity.',
		link: '/consultations/name-correction',
		image: '/images/services/name-correction.webp',
		currentPrice: 5100,
		actualPrice: Math.ceil(5100 / 0.7),
		offering: [
			'Detailed Name Analysis: Using Chaldean, Pythagorean and Vedic charts, we provide a comprehensive analysis of your name.',
			'Personalized Correction: Tailored name corrections that align with your personal numerology and life goals.',
			'Energy Enhancement: Enhance the vibrational energy of your name to attract positive opportunities and experiences.',
			'Professional Guidance: Receive one-to-one counseling to understand the significance of the changes and how to integrate them into your life.',
		],
		benefits: [
			'Improved personal and professional relationships',
			'Increased confidence and self-awareness',
			'Enhanced opportunities and success',
			'Greater harmony and balance in life',
		],
	},
	{
		title: 'Personal Consultation',
		slug: 'personal-consultation',
		tagline: 'Numerology-based guidance for personal consultation',
		description:
			'Get expert numerology consultation for Personal Consultation. Align energies for improved harmony and outcomes in life.',
		link: '/consultations/personal-consultation',
		image: '/images/services/placeholder.webp',
		currentPrice: 1500,
		actualPrice: Math.ceil(1500 / 0.7),
		offering: [
			'Comprehensive Personal Consultation analysis based on your unique numerology chart.',
			'Personalized recommendations and remedies tailored to your goals.',
			'One-on-one consultation to discuss insights and implementation.',
		],
		benefits: [
			'Better clarity and alignment with life goals',
			'Improved decision-making and confidence',
			'Enhanced personal and professional outcomes',
		],
	},
	{
		title: 'Wedding Date Consultation',
		slug: 'wedding-date-consultation',
		tagline: 'Numerology-based guidance for wedding date consultation',
		description:
			'Get expert numerology consultation for Wedding Date Consultation. Align energies for improved harmony and outcomes in life.',
		link: '/consultations/wedding-date-consultation',
		image: '/images/services/placeholder.webp',
		currentPrice: 1100,
		actualPrice: Math.ceil(1100 / 0.7),
		offering: [
			'Comprehensive Wedding Date Consultation analysis based on your unique numerology chart.',
			'Personalized recommendations and remedies tailored to your goals.',
			'One-on-one consultation to discuss insights and implementation.',
		],
		benefits: [
			'Better clarity and alignment with life goals',
			'Improved decision-making and confidence',
			'Enhanced personal and professional outcomes',
		],
	},
	{
		title: 'Watch Analysis',
		slug: 'watch-analysis',
		tagline: 'Numerology-based guidance for watch analysis',
		description:
			'Get expert numerology consultation for Watch Analysis. Align energies for improved harmony and outcomes in life.',
		link: '/consultations/watch-analysis',
		image: '/images/services/placeholder.webp',
		currentPrice: 1100,
		actualPrice: Math.ceil(1100 / 0.7),
		offering: [
			'Comprehensive Watch Analysis based on numerological influence.',
			'Suggestions on suitable watches aligned with your energy.',
			'One-on-one session to explain time-energy balance.',
		],
		benefits: [
			'Improved alignment of personal time and goals',
			'Better vibrational balance throughout the day',
			'Enhanced energy utilization and focus',
		],
	},
	{
		title: 'Business Name',
		slug: 'business-name',
		tagline: 'Numerology-based guidance for business name',
		description:
			'Get expert numerology consultation for Business Name. Align energies for improved harmony and outcomes in life.',
		link: '/consultations/business-name',
		image: '/images/services/placeholder.webp',
		currentPrice: 5100,
		actualPrice: Math.ceil(5100 / 0.7),
		offering: [
			'Business name energy evaluation using numerological charts.',
			'Correction suggestions based on business goals.',
			'One-on-one discussion to explain rationale and benefits.',
		],
		benefits: [
			'Better brand perception and public resonance',
			'More business opportunities and positive visibility',
			'Increased vibrational alignment for growth',
		],
	},
	{
		title: 'Business Consultation',
		slug: 'business-consultation',
		tagline: 'Elevate Your Business with Our Strategic Numerology Consultation',
		description:
			"Unlock the hidden potential of your business with our specialized numerology consultation. Whether you're a startup or an established enterprise, Akreti Verma provides strategic insights to enhance your business success.",
		link: '/consultations/business-consultation',
		image: '/images/services/business-consultation.webp',
		currentPrice: 3100,
		actualPrice: Math.ceil(3100 / 0.7),
		offering: [
			'Business Name Analysis and Correction',
			'Strategic Planning',
			'Employee and Team Analysis',
			'Financial Forecasting',
			'Vastu Consultation for Office Spaces',
		],
		benefits: [
			'Improved brand resonance and market appeal',
			'Enhanced decision-making and strategic planning',
			'Greater team harmony and productivity',
			'Optimal financial management and growth',
		],
	},
	{
		title: 'Vastu Consultation',
		slug: 'vastu-consultation',
		tagline: 'Numerology-based guidance for vastu consultation',
		description:
			'Get expert numerology consultation for Vastu Consultation. Align energies for improved harmony and outcomes in life.',
		link: '/consultations/vastu-consultation',
		image: '/images/services/placeholder.webp',
		currentPrice: 5100,
		actualPrice: Math.ceil(5100 / 0.7),
		offering: [
			'Vastu-compliant space planning aligned with numerology.',
			'Correction suggestions using yantras, crystals, and placements.',
			'Detailed consultation for home/office layout balance.',
		],
		benefits: [
			'Improved flow of positive energy',
			'Better harmony and mental clarity',
			'Enhanced family/professional success',
		],
	},
	{
		title: 'Baby Care Package',
		slug: 'baby-care-package',
		tagline: 'Numerology-based guidance for baby care package',
		description:
			'Get expert numerology consultation for Baby Care Package. Align energies for improved harmony and outcomes in life.',
		link: '/consultations/baby-care-package',
		image: '/images/services/placeholder.webp',
		currentPrice: 2100,
		actualPrice: Math.ceil(2100 / 0.7),
		offering: [
			'Numerology chart analysis of baby.',
			'Parenting advice based on elemental energies.',
			'Early remedies and practices for growth.',
		],
		benefits: [
			'Healthier physical and emotional development',
			'Better bonding and behavior understanding',
			'Foundation of aligned early life choices',
		],
	},
	{
		title: 'Baby Name Suggestions',
		slug: 'baby-name-suggestions',
		tagline: 'Numerology-based guidance for baby name suggestions',
		description:
			'Get expert numerology consultation for Baby Name Suggestions. Align energies for improved harmony and outcomes in life.',
		link: '/consultations/baby-name-suggestions',
		image: '/images/services/placeholder.webp',
		currentPrice: 1500,
		actualPrice: Math.ceil(1500 / 0.7),
		offering: [
			'Name shortlisting based on birth chart and numerology.',
			'Multiple name suggestions with meanings.',
			'Discussion on family and cultural preferences.',
		],
		benefits: [
			'Energetically harmonious name for life success',
			'Positive personality and future alignment',
			'Improved health, bonding, and academic flow',
		],
	},
	{
		title: 'Match Compatibility',
		slug: 'match-compatibility',
		tagline: 'Numerology-based guidance for match compatibility',
		description:
			'Get expert numerology consultation for Match Compatibility. Align energies for improved harmony and outcomes in life.',
		link: '/consultations/match-compatibility',
		image: '/images/services/placeholder.webp',
		currentPrice: 1500,
		actualPrice: Math.ceil(1500 / 0.7),
		offering: [
			'Partner compatibility through birth numbers and life paths.',
			'Analysis of strengths and challenges in relationship.',
			'Suggested remedies and energy enhancers.',
		],
		benefits: [
			'Better emotional bonding and communication',
			'Improved long-term relationship alignment',
			'Clarity on mutual growth potential',
		],
	},
	{
		title: 'Mobile Number Analysis',
		slug: 'mobile-number-analysis',
		tagline: 'Numerology-based guidance for mobile number analysis',
		description:
			'Get expert numerology consultation for Mobile Number Analysis. Align energies for improved harmony and outcomes in life.',
		link: '/consultations/mobile-number-analysis',
		image: '/images/services/placeholder.webp',
		currentPrice: 1100,
		actualPrice: Math.ceil(1100 / 0.7),
		offering: [
			'Energy evaluation of your current number.',
			'Suitability check with life path number.',
			'Improvement tips or recommended new number.',
		],
		benefits: [
			'Better personal and professional luck flow',
			'Increased synchronicity and opportunity',
			'Vibrational harmony in daily communication',
		],
	},
	{
		title: 'Energized Crystal Recommendation',
		slug: 'energized-crystal-recommendation',
		tagline: 'Enhance Your Life with Our Crystal Recommendation Service',
		description:
			'Enhance your life with personalized crystal recommendations. Akreti Verma combines numerology with crystal healing to guide you in selecting the perfect crystals for emotional healing, spiritual growth, and personal goals.',
		link: '/consultations/energized-crystal-recommendation',
		image: '/images/services/energized-crystal-recommendation.webp',
		currentPrice: 1100,
		actualPrice: Math.ceil(1100 / 0.7),
		offering: [
			'Personalized Crystal Analysis: Crystals tailored to your numerological profile and life goals.',
			'Customized Recommendations: Guidance on selecting crystals for emotional healing, focus, or spiritual growth.',
			'Effective Usage Tips: Instructions on how to cleanse, charge, and meditate with your crystals.',
			'Complementary Practices: Techniques that enhance crystal benefits through affirmations and rituals.',
			'Professional Consultation: One-on-one sessions to discuss goals and challenges.',
		],
		benefits: [
			'Improved emotional balance and healing',
			'Enhanced focus, clarity, and spiritual growth',
			'Greater alignment with personal and professional goals',
			'Increased positive energy and well-being',
		],
	},
];
